name = "portofolio"
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB"
database_name = "portofolio-db"
database_id = "6ed1d446-8ff0-4ca5-b24e-8eb14aa254bc"

[[kv_namespaces]]
binding = "KV"
id = "40249f5514ff4423b980743c73adc903"

[[r2_buckets]]
binding = "R2"
bucket_name = "portofolio-assets"

[vars]
ENVIRONMENT = "production"
GROQ_API_KEY = "PASTE_YOUR_GROQ_API_KEY_IN_DASHBOARD"
SITE_URL = "http://localhost:4321"
BETTER_AUTH_SECRET = "PASTE_YOUR_AUTH_SECRET_IN_DASHBOARD"
ADMIN_EMAILS = "muhammadulyafarhan@gmail.com"
PUBLIC_R2_URL = "http://localhost:4321/uploads"

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTOR_INDEX"
index_name = "proyek-index"
